#!/bin/sh
# by Cygnus
# cygnus@ncohafmuta.com
#
SIG=$1
BINARY="server"

if test -f "./$BINARY.pid"
then
echo -n "Shutting down talker.."

if test "$SIG" = ""
then
	kill -USR1 `cat $BINARY.pid`
else
	kill -$SIG `cat $BINARY.pid`
fi
echo "talker is off."
else
	echo "Cant find $BINARY.pid file! Is talker really running to begin with?"
fi
